### PR TITLE
compile test report script and run from .jar file

### PR DESCRIPTION
**Pull request by vordimous**
This will improve the run time of tests for individual exercise submissions

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@iHiD @ErikSchierboom  can you reopen this?

**Comment by iHiD** [comment]
Pls merge https://github.com/exercism/ballerina-test-runner/pulls to stop your PRs from being closed.

**Review by ErikSchierboom — APPROVED** [review]
LGTM and CI is green!

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Feel free to merge @vordimous. Deployment is automatic

**Pull request merged**
