### PR TITLE
add individual dependency pull

### PR DESCRIPTION
**Pull request by vordimous**
This is a simple way to ensure the necessary dependencies are included. this is based on the fsharp method https://github.com/exercism/fsharp-test-runner/blob/main/Dockerfile#L19-L20

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I won't have time to review now, but I'll do it next week (tuesday). Sorry!

**Review by ErikSchierboom — APPROVED** [review]
LGTM

**Comment by vordimous** [comment]
@ErikSchierboom What is left to get the [Ballerina](https://exercism.org/tracks/ballerina) track enabled?

**Comment by ErikSchierboom** [comment]
@vordimous The biggest thing is to (re-)add more exercises. Some of the deleted exercises have not yet been restored: https://github.com/exercism/ballerina/pull/140/files At a minimum they should be re-added. Apart from that we usually launch with about 20 exercises implemented. Note that you don't have to come up with these from scratch, we have a separate repository with sample exercises that you can implement. See https://exercism.org/docs/building/tracks/new/add-initial-exercises

Secondly, the test runner needs to be enabled in order to be able to test whether it works. That is done by setting the `status.test_runner` field to `true` and to add `test_runner.average_run_time` field.

**Comment by vordimous** [comment]
@ErikSchierboom Ok, great I will work on those old exercises and update or deprecate them as needed. We also have 20 more questions coming from a different event we held this year. I am working on adding them:
image

**Comment by ErikSchierboom** [comment]
That looks great!

**Pull request merged**
