### PR TITLE
Remove unneeded mkdir

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This will ensure that the deploy script can build the image.

CC @vordimous

### CODE REVIEW

**Comment by vordimous** [comment]
@ErikSchierboom This change will allow the tests to work, however the dependency pulls in a `--network none` environment will fail. I can make sure all of the dependencies in the test cases won't require a network, but doing so for the solutions will quickly become a maintenance headache. 

The `bal build` command has to run at container build time with access to the internet, so adding the `/solution` as a volume will not allow for the library caching to happen. If we don't run the `bal build` on the incoming project, it could have mismatched dependencies and will throw an error.

Separately if we will always control the `ballerina.toml` and `dependancy.toml` files and ignore user changes to those, then we may be able to avoid the issue altogether and remove the repo_cache. However, this may limit some of the exercise cases as we will force the use of specific libraries in the solution. The bigger problem will happen when a minor version update happens every exercise will need to be updated to match the version in the docker image. 

I know this is a crazy requirement, and I have already created a few tickets for the Ballerina team to help make this process cleaner. I can jump on a call to help come up with a solution if necessary.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom This change will allow the tests to work, however the dependency pulls in a --network none environment will fail. I can make sure all of the dependencies in the test cases won't require a network, but doing so for the solutions will quickly become a maintenance headache.

But this also wasn't solved by the previous code. I've only removed the `mdkir` bit and used on exercise (the others didn't have the toml files).

> The bal build command has to run at container build time with access to the internet, so adding the /solution as a volume will not allow for the library caching to happen.

But this is still happening with these changes.

>  If we don't run the bal build on the incoming project, it could have mismatched dependencies and will throw an error.

Yes, that is something that all test runners have to deal with.

> Separately if we will always control the ballerina.toml and dependancy.toml files and ignore user changes to those, then we may be able to avoid the issue altogether and remove the repo_cache. However, this may limit some of the exercise cases as we will force the use of specific libraries in the solution. 

The way we solve this for other tracks is to only allow specific libraries to be used (a _whitelist_ of libraries). As we don't have internet whilst running the test runner, we can't just arbitrarily download any library. That is by design.

> The bigger problem will happen when a minor version update happens every exercise will need to be updated to match the version in the docker image.

Could ballerina be configured to roll forward automatically? As in: if there is a higher minor version, couldn't it use that? If not, you could consider install multiple versions of a package in order to remain backwards compatible once they change.

> ballerina.toml and dependancy.toml

As I suggested in a similar issue for the gleam track (see https://github.com/exercism/gleam/issues/113), you probably want to add the `ballerina.toml` and `dependancy.toml` files as `invalidator` files. That way, updating those files will prompt students to upgrade.

**Comment by vordimous** [comment]
There are two issues right now.
1. I don't understand Exercism dependency management, and I am guessing there is some global caching involved.
2. Ballerina dependency caching is not very friendly. Only the `bal run/test/build` commands fetch all of the deps, and they will automatically update the dependency.toml file based on what is being included in the project. The goal is to be dynamic and "not have to think about it." This is what makes it hard for this use case...

Two action items:
- [x]  remove the `bal build` altogether
```
COPY tests/example-success/ .
RUN bal build
```
This is only needed during the `test-run-in-docker.sh` CI to ensure older libs are being downloaded and used correctly. The dependencies in the test exercises can be managed statically to ensure there won't be a remote fetch.

- [x] The `bal build` command needs to be executed somewhere with access to the internet, and the `/root/.ballerina/repositories` directory should be cached and mounted into the `ballerina-test-runner` container. 

I think it is best to solve those two cases before continuing. Adding the `ballerina.toml` and `dependancy.toml` files as invalidator files is a good idea, I'll start on that effort, but it won't solve the problem.

**Comment by vordimous** [comment]
Ok, I came up with a cleaner solution. Let me know what you think over on this PR: https://github.com/exercism/ballerina-test-runner/pull/5

**Comment by iHiD** [comment]
@vordimous 👋 The workflow is that the Docker image gets build via a GitHub action where it has internet access. After that point, when containers are spawned from the image, it will never have internet access again. We copy the code from `exercism/ballerina` and the student's code onto the machine, and then execute it We do no dependency management or anything else beyond that.

**Comment by ErikSchierboom** [comment]
@vordimous Regarding that PR, I'm afraid that approach won't work, as the solution is only available whilst running the docker image, at which point there is no internet connection. 

It might also be good for you to know that the `run-in-docker.sh` script isn't actually called by the website, it is just there for local testing. 

As Jeremy said, the steps are:

1. Once a PR is merged to `main`, the `deploy.yml` workflow will automatically run
2. The deploy workflow will build the docker image using `docker build -t exercism/ballerina-test-runner .` 
  - It is important to note that at this point, there is no such thing as a solution, as this runs in our github CI
  - It is also important to note that you do have access to the internet in this step, so the Dockerfile is built using internet (which is why you can download things within the Dockerfile)
3. The deploy workflow will push the built container to AWS ECR

Then, when a student submits a solution:

1. We copy the exercise's code from the `exercism/ballerina` repo
2. We then add the student's submitted code to that directory
3. We run the Docker image that was built previously on that directory, to test the student's solution
4. Whilst running the Docker image, it is important to note that there is no internet connection

Taking this all into account, the **only** way in which you can support packages being used by the student is to pre-download them into the Docker image at build time (so within the `Dockerfile`).

**Comment by vordimous** [comment]
I don't understand how that flow works for languages like golang and javascript, the exercises have a static go.mod or package.json file. Is the student pushing `node_modules` or `/go/root` packages with their solution, or are those dependencies fetched and stored for the exercise itself?

Maybe I can replicate this [deps.go](https://github.com/exercism/go-test-runner/blob/main/external-packages/deps.go) from the go runner. I am guessing this happens in the `Once a PR is merged to main, the deploy.yml workflow will automatically run` step.

**Comment by ErikSchierboom** [comment]
> I don't understand how that flow works for languages like golang and javascript, the exercises have a static go.mod or package.json file. Is the student pushing node_modules or /go/root packages with their solution, or are those dependencies fetched and stored for the exercise itself?

Let me quote myself :)

> Taking this all into account, the only way in which you can support packages being used by the student is to pre-download them into the Docker image at build time (so within the Dockerfile).

> Maybe I can replicate this [deps.go](https://github.com/exercism/go-test-runner/blob/main/external-packages/deps.go) from the go runner. I am guessing this happens in the Once a PR is merged to main, the deploy.yml workflow will automatically run step.

What do you mean by "this happens"? I assume you mean: download additional packages. If so, this is done in the `Dockerfile`. See https://github.com/exercism/go-test-runner/commit/a7c176dc712330c43b2404e0bbe8b977a02c2124 for the Go example.

**Comment by iHiD** [comment]
@vordimous What external packages does a student need for Ballerina?

**Comment by vordimous** [comment]
The Ballerina std libs have specific versions that match the minor version of Ballerina they are built from. How it was explained to me:
```
io 1.2.2 has been published using 2201.0.4 and so it will be resolved by all newer 2201.0.x distributions
io 1.3.0 has been published using 2201.2.0 and so it be resolved by 2201.2.x distributions but not with 2201.1.x or 2201.0.x dist versions
2201.2.x distributions will fetch any io 1.2 and lower versions and stored in <userhome>/.ballerina/repositories

```
The current version in the dockerfile is above the [io version in the exercise repo](https://github.com/exercism/ballerina/blob/main/exercises/practice/hello-world/Dependencies.toml#L12), meaning the 1.2.2 lib will need to be fetched from the ballerina.central registry. 

The reason I want to figure out this dep caching option is to eliminate a maintenance need in the future when we simply upgrade the ballerina dist version.

I apologize for the difficulties. The ballerina dep management isn't ideal.

**Comment by ErikSchierboom** [comment]
> The current version in the dockerfile is above the [io version in the exercise repo](https://github.com/exercism/ballerina/blob/main/exercises/practice/hello-world/Dependencies.toml#L12), meaning the 1.2.2 lib will need to be fetched from the ballerina.central registry.

You could predownload multiple versions of the same package, see https://github.com/exercism/fsharp-test-runner/blob/main/Dockerfile#L19-L20

**Comment by vordimous** [comment]
> You could predownload multiple versions of the same package, see https://github.com/exercism/fsharp-test-runner/blob/main/Dockerfile#L19-L20

Thank You! This is probably the simplest way and will get us past this step. This PR should work https://github.com/exercism/ballerina-test-runner/pull/7

I created a draft PR with this process that pulls and caches deps based on what is in the ballerina/exercise dir https://github.com/exercism/ballerina-test-runner/pull/8

**Pull request merged**
